print('L            K     k     G G G G G G G G')
print('L            K   k       G              ')
print('L            K  k        G              ')
print('L            K K         G              ')
print('L            KK          G     G G G G G')
print('L            K K         G             G')
print('L            K  k        G             G')
print('L            K   k       G             G')
print('L L L L L    K     k     G G G G G G G G')